minEnergyLogThreshold: 100
teleporter:
  maxBounce: 256
energy:
  multipliers:
    ore: 1.5
    chainmail: 1.1
    crafting: 1.05
  maxBurnDistance: 30
  costs:
    move: 0.2
    blockBreak: 8
    smelt: 5
    damage: 5
    absorb: 30
    heal: 15